version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:80"
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
    working_dir: /backend/QVtoolapi/ 
    environment:
      - PRODUCTION=True
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always

  web:
    build:
      context: .
      dockerfile: ./PDockerfile
    command: serve -s build -l 3000
    volumes:
    - ./polis-app/src:/polis-app/src
    ports:
      - "3000:30"
    depends_on:
      - api
    environment:
      - REACT_APP_SITE_ID=$REACT_APP_SITE_ID
    stdin_open: true
    restart: always

volumes:
  db-data:
