version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
    working_dir: /backend/QVtoolapi/
    environment:
      - PRODUCTION=True
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    restart: always

  nginx:
    image:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/QVtoolapi/static:/var/www/backend
    depends_on:
      - api
    restart: always

volumes:
  db-data:
